---
- hosts: 172.31.93.76
  become: yes
  tasks:
   - include_tasks: myfiles.yml
   - name: create a folder
     file:
      path: /home/ubuntu/myfolder
      state: directory

   - name: i want to copy files
     copy:
      src: mystaticfile
      dest: /home/ubuntu/mystaticfile.txt

   - name: install apache2
     apt: 
      name: apache2
      state: present

   - name: copy dynamic file
     template:
      src: myindex.j2
      dest: /var/www/html/index.html   

   
   - name: download jenkins.war files
     get_url:
      url: https://get.jenkins.io/war-stable/2.361.1/jenkins.war
      dest: /home/ubuntu/jenkins.war
      force_basic_auth: yes   