---
- hosts: 172.31.31.78
  become: yes
  tasks:
   - include_tasks: myfiles.yml
   - name: create a folder
     file:
      path: /home/ubuntu/myfolder
      state: directory

   - name: i want to copy files
     copy:
      src: my state file
      dest: /home/ubuntu/mystaticfile.txt
